kind: Cluster
name: omni-contrib
talos:
  version: v1.7.4
kubernetes:
  version: 1.28.6
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: omni-contrib-controlplane
  size: 1
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machines:
  - 4c4c4544-0037-5a10-8030-c8c04f4a5132
  - 00000000-0000-0000-0000-ac1f6b58ada8
# machineClass:
#   name: omni-contrib-workers
#   size: unlimited
---
kind: Machine
name: 4c4c4544-0037-5a10-8030-c8c04f4a5132
patches:
  - file: patches/gpu-worker-patch.yaml
systemExtensions:
    - nvidia-open-gpu-kernel-modules
    - nvidia-container-toolkit
