kind: Cluster
name: omni-contrib
talos:
  version: v1.7.4
kubernetes:
  version: 1.28.6
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: omni-controlplane
  size: 1
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers-cpu
machineClass:
  name: omni-cpu-workers
  size: 1
---
kind: Workers
name: workers-gpu
machineClass:
  name: omni-gpu-workers
  size: 1
patches:
  - file: patches/gpu-worker-patch.yaml